name: build

on:
  workflow_dispatch:
  push:
    paths:
    - "**.js"
    - "**.cjs"
    - "**.mjs"
    - "**.json"
  pull_request:

jobs:
  test_and_coverage:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.x, 15.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: | 
        npm ci
        npm run coverage
    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: jest-stare
