name: build

on:
  workflow_dispatch:
  push:
    paths:
    - "**.js"
    - "**.cjs"
    - "**.mjs"
    - "**.json"
  pull_request:

jobs:
  test_and_coverage:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.x, 16.x]

    env:
      NODEJS: ${{ matrix.node-version }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.4.1
      with:
        node-version: ${{ matrix.node-version }}
    - run: | 
        npm ci
        npm run lint
        npm run coverage:ci
    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: test-report-node${{ matrix.node-version }}
        path: jest-stare
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        directory: ./coverage/
        fail_ci_if_error: true
        env_vars: NODEJS
