name: build

on:
  workflow_dispatch:
  push:
    paths:
    - "**.js"
    - "**.cjs"
    - "**.mjs"
    - "**.json"
  pull_request:

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    env:
      NODEJS: ${{ matrix.node-version }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.6.0
      with:
        node-version: ${{ matrix.node-version }}
    - run: | 
        npm ci
        npm run lint
        npm run coverage:ci
    - name: Archive test results
      uses: actions/upload-artifact@v3
      with:
        name: test-report-node${{ matrix.node-version }}
        path: jest-stare
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3.1.4
      with:
        directory: ./coverage/
        fail_ci_if_error: true
        env_vars: NODEJS
