name: Release

on:
  push:
    tags:
    - "v[0-9].[0-9]+.[0-9]+"

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
      - uses: actions/checkout@v3
      - name: Lint and test
        run: | 
          npm ci
          npm run lint
          npm test
      - name: Build and pack
        run: |
          npm version --no-git-tag-version from-git
          npm run build:production
          cp LICENSE ./dist/
          mkdir release
          cd dist
          rm manifest-v2.json
          zip -r ../release/yt_chapters_ext.zip ./*
          cd ..
          rm -rf dist
          npm run build:firefox:production
          cp LICENSE ./dist/
          cd dist
          rm manifest-v2.json
          zip -r ../release/yt_chapters_ext_firefox.zip ./*
      - name: Create Release and upload assets
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: release/*.zip
