name: Release

on:
  push:
    tags:
    - "v[0-9].[0-9]+.[0-9]+"

  workflow_dispatch:
    inputs:
      tag:
        description: Tag (version)
        required: true

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16
      - name: Get tag
        id: get-tag
        uses: actions/github-script@v3
        with:
          result-encoding: string
          script: |
            const ref = context.ref
            console.log(`Evaluating ref='${ ref }'`)
            const tag = ref.startsWith("refs/tags") ? ref.substring(10) : context.payload.inputs.tag
            return tag
      - uses: actions/checkout@v2
        with:
          ref: refs/tags/${{ steps.get-tag.outputs.result }}
      - name: Lint and test
        run: | 
          npm ci
          npm run lint
          npm test
      - name: Build and pack
        run: |
          npm version --no-git-tag-version from-git
          npm run build:production
          cp LICENSE ./dist/
          mkdir release
          cd dist
          zip -r ../release/yt_chapters_ext.zip ./*
      - name: Create Release and upload assets
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: release/*.zip
