name: Release

on:
  push:
    tags:
    - "v[0-9].[0-9]+.[0-9]+"

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.3.0
        with:
          node-version: 15
      - name: Lint and test
        run: | 
          npm ci
          npm run lint
          npm test
      - name: Build
        run: |
          npm run build
          cp LICENSE ./dist/
          mkdir release
          cd dist
          zip -r ../release/yt_chapters_chrome_ext.zip ./*
      - name: Create Release and upload assets
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALLOW_TAG_PREFIX: "true"
        with:
          args: release/*.zip